### ISSUE TITLE
List emotes without spaces

### ISSUE THREAD

**Issue by rollingmoai** [Vendicated/PowercordReacter#2]
Right now spaces are needed to each emote that is put. This is annoying as you have to put spaces on each emote after shift-clicking multiple emotes from the emote menu.

**Comment by Vendicated** [comment]
Good idea! this is gonna be a bit tough with default emojis but I'll figure it out

**Comment by Vendicated** [comment]
Should be fixed now, let me know if theres any more issues

**Comment by rollingmoai** [comment]
Everything seems to be working well now, thanks!
