### ISSUE TITLE
Cannot react when someone else has reacted to it

### ISSUE THREAD

**Issue by rollingmoai** [Vendicated/PowercordReacter#3]
Cannot react when someone else has reacted to it when the emote itself is given. However, it works when you only type the emote name.

**Comment by Vendicated** [comment]
This was a bug in an older version but I'm pretty sure I fixed it. Can you update via the powercord settings and try again?

**Comment by rollingmoai** [comment]
Hmm. This happens on the latest commit (also I tried it again).

**Comment by rollingmoai** [comment]
Oh, Fixing the bug at #1 (`match[0]`) fixes this issue as well.

**Comment by Vendicated** [comment]
👍 awesome! I'll fix #1 and implement #2 in a bit, thank you!

**Comment by Vendicated** [comment]
This was caused because my hasReacted check had a false positive if you reacted with another emote that has the same name. I fixed this too along with the other fixes, now if the emoji has an id it will check only the id, otherwise it checks only the name
