### ISSUE TITLE
add fuzzy support

### ISSUE THREAD

**Issue by untuned** [Vendicated/PowercordReacter#4]
I would like it so that if I were to search for just "default" (or optionally "default*"), then it will search based on that word and other inclusions.

**Comment by JakeyPrime** [comment]
I would also like to see this, I have like 90 :flushed: emotes that I want to add sometimes, but they aren't always called :flushed:, having similar emotes or even a subargument of the main command to add all similar emotes would be awesome.

**Comment by Vendicated** [comment]
I could implement support for one single wildcard per search (normal* to match anything starting with normal, *normal to match anything ending with normal and nor*mal to match anything starting with nor and ending with mal). anything else would be way too complex and probably not very performant

**Comment by JakeyPrime** [comment]
> I could implement support for one single wildcard per search (normal* to match anything starting with normal, *normal to match anything ending with normal and nor*mal to match anything starting with nor and ending with mal). anything else would be way too complex and probably not very performant

I think this would be completely fine since yeah, you are right, searching for all versions or similar versions of an emote with similar names would not be performant. I think a single wildcard search would be more than fine, at least for me.

**Comment by Vendicated** [comment]
Implemented via https://github.com/Vendicated/PowercordReacter/commit/091aa51414e478e73dcc41528a2bdef4d99cfb4b, thansk for the suggestion!
